// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class OneCallResponseHourlyRain
    {
        [JsonPropertyName("1h")]
        public double H { get; set; }
    }
}
