// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class OneCallResponseHourly
    {
        [JsonPropertyName("clouds")]
        public byte Clouds { get; set; }

        [JsonPropertyName("dew_point")]
        public double DewPoint { get; set; }

        [JsonPropertyName("dt")]
        public uint Dt { get; set; }

        [JsonPropertyName("feels_like")]
        public double FeelsLike { get; set; }

        [JsonPropertyName("humidity")]
        public byte Humidity { get; set; }

        [JsonPropertyName("pop")]
        public double Pop { get; set; }

        [JsonPropertyName("pressure")]
        public ushort Pressure { get; set; }

        [JsonPropertyName("temp")]
        public double Temp { get; set; }

        [JsonPropertyName("uvi")]
        public double Uvi { get; set; }

        [JsonPropertyName("visibility")]
        public ushort Visibility { get; set; }

        [JsonPropertyName("weather")]
        public IList<OneCallResponseHourlyWeather> Weather { get; set; }

        [JsonPropertyName("wind_deg")]
        public byte WindDeg { get; set; }

        [JsonPropertyName("wind_gust")]
        public double WindGust { get; set; }

        [JsonPropertyName("wind_speed")]
        public double WindSpeed { get; set; }

        [JsonPropertyName("rain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public OneCallResponseHourlyRain Rain { get; set; }
    }
}
