// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class OneCallResponseDaily
    {
        [JsonPropertyName("clouds")]
        public byte Clouds { get; set; }

        [JsonPropertyName("dew_point")]
        public double DewPoint { get; set; }

        [JsonPropertyName("dt")]
        public uint Dt { get; set; }

        [JsonPropertyName("feels_like")]
        public OneCallResponseDailyFeelsLike FeelsLike { get; set; }

        [JsonPropertyName("humidity")]
        public byte Humidity { get; set; }

        [JsonPropertyName("moon_phase")]
        public double MoonPhase { get; set; }

        [JsonPropertyName("moonrise")]
        public uint Moonrise { get; set; }

        [JsonPropertyName("moonset")]
        public uint Moonset { get; set; }

        [JsonPropertyName("pop")]
        public double Pop { get; set; }

        [JsonPropertyName("pressure")]
        public ushort Pressure { get; set; }

        [JsonPropertyName("sunrise")]
        public uint Sunrise { get; set; }

        [JsonPropertyName("sunset")]
        public uint Sunset { get; set; }

        [JsonPropertyName("temp")]
        public OneCallResponseDailyTemp Temp { get; set; }

        [JsonPropertyName("uvi")]
        public double Uvi { get; set; }

        [JsonPropertyName("weather")]
        public IList<OneCallResponseDailyWeather> Weather { get; set; }

        [JsonPropertyName("wind_deg")]
        public byte WindDeg { get; set; }

        [JsonPropertyName("wind_gust")]
        public double WindGust { get; set; }

        [JsonPropertyName("wind_speed")]
        public double WindSpeed { get; set; }

        [JsonPropertyName("rain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public double? Rain { get; set; }
    }
}
