// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class OneCallResponseMinutely
    {
        [JsonPropertyName("dt")]
        public uint Dt { get; set; }

        [JsonPropertyName("precipitation")]
        public byte Precipitation { get; set; }
    }
}
