// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class OneCallResponseAlert
    {
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonPropertyName("end")]
        public uint End { get; set; }

        [JsonPropertyName("event")]
        public string Event { get; set; }

        [JsonPropertyName("sender_name")]
        public string SenderName { get; set; }

        [JsonPropertyName("start")]
        public uint Start { get; set; }

        [JsonPropertyName("tags")]
        public IList<string> Tags { get; set; }
    }
}
