// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class CurrentAndForecastResponse
    {
        [JsonPropertyName("alerts")]
        public IEnumerable<Alert> Alerts { get; set; }

        [JsonPropertyName("current")]
        public Current Current { get; set; }

        [JsonPropertyName("daily")]
        public IEnumerable<Daily> Daily { get; set; }

        [JsonPropertyName("hourly")]
        public IEnumerable<Hourly> Hourly { get; set; }

        [JsonPropertyName("lat")]
        public float Lat { get; set; }

        [JsonPropertyName("lon")]
        public float Lon { get; set; }

        [JsonPropertyName("minutely")]
        public IEnumerable<Minutely> Minutely { get; set; }

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; }

        [JsonPropertyName("timezone_offset")]
        public int TimezoneOffset { get; set; }
    }
}
