// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class Daily
    {
        [JsonPropertyName("clouds")]
        public int Clouds { get; set; }

        [JsonPropertyName("dew_point")]
        public float DewPoint { get; set; }

        [JsonPropertyName("dt")]
        public int Dt { get; set; }

        [JsonPropertyName("feels_like")]
        public FeelsLike FeelsLike { get; set; }

        [JsonPropertyName("humidity")]
        public int Humidity { get; set; }

        [JsonPropertyName("moon_phase")]
        public float MoonPhase { get; set; }

        [JsonPropertyName("moonrise")]
        public int Moonrise { get; set; }

        [JsonPropertyName("moonset")]
        public int Moonset { get; set; }

        [JsonPropertyName("pop")]
        public float Pop { get; set; }

        [JsonPropertyName("pressure")]
        public int Pressure { get; set; }

        [JsonPropertyName("sunrise")]
        public int Sunrise { get; set; }

        [JsonPropertyName("sunset")]
        public int Sunset { get; set; }

        [JsonPropertyName("temp")]
        public Temperature Temp { get; set; }

        [JsonPropertyName("uvi")]
        public float Uvi { get; set; }

        [JsonPropertyName("weather")]
        public IEnumerable<Weather> Weather { get; set; }

        [JsonPropertyName("wind_deg")]
        public int WindDeg { get; set; }

        [JsonPropertyName("wind_gust")]
        public float WindGust { get; set; }

        [JsonPropertyName("wind_speed")]
        public float WindSpeed { get; set; }

        [JsonPropertyName("rain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? Rain { get; set; }
    }
}
