// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class Minutely
    {
        [JsonPropertyName("dt")]
        public int Dt { get; set; }

        [JsonPropertyName("precipitation")]
        public int Precipitation { get; set; }
    }
}
