// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace VL.OpenWeather
{
    public class Temperature
    {
        [JsonPropertyName("day")]
        public float Day { get; set; }

        [JsonPropertyName("eve")]
        public float Eve { get; set; }

        [JsonPropertyName("max")]
        public float Max { get; set; }

        [JsonPropertyName("min")]
        public float Min { get; set; }

        [JsonPropertyName("morn")]
        public float Morn { get; set; }

        [JsonPropertyName("night")]
        public float Night { get; set; }
    }
}
